config/routes.rb
PgMenage::Application.routes.draw do
  root :to => "home#index"
  resources :content

end

app/models/article.rb
class Article < Content
  set_table_name "articles"
  validates_presence_of :body, :if => Proc.new {|c| c.published?}
end

app/models/content.rb
class Content < ActiveRecord::Base
  include PgArelHack
  scope :published, :conditions => "start_date <= now()::date and (end_date is null or end_date > now()::date) and published"
  
  validates_presence_of :title
  validates_presence_of :start_date

  attr_accessor :kind

  cattr_accessor :children
  
  def get_origin_type
    connection.select_value(
    "select p.relname
     from content c, pg_class p
     where c.tableoid = p.oid and c.id = #{id}"
     ).classify.constantize.find(id)
  end
  
  class << self
  
    def children
      unless @@children
        main_oid = connection.select_value("select attrelid from pg_attribute where attrelid = '#{self.to_s.tableize}'::regclass limit 1;")
        @@children = []
        add_children(main_oid)
      end
      @@children
    end

    private
  
      def add_children(parent_oid)
        inherited_children = connection.select_values("select inhrelid from pg_inherits where inhparent = #{parent_oid};")
        inherited_children.each do |child|
          child_name = connection.select_value("select relname from pg_class where oid = #{child}")
          @@children << child_name.classify.constantize
          add_children(child)
        end
      end
    
  end

end

app/models/news.rb
class News < Article
  set_table_name "news"
  validates_presence_of :synopsis, :if => Proc.new {|c| c.published?}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/content_controller.rb
class ContentController < ApplicationController

  def new
    @content = Content.new
  end

  def create
    @content = Content.new(params[:content])
    @content = @content.becomes(@content.kind.constantize)
    if @content.save
      flash[:success] = "#{@content.kind} created"
      redirect_to edit_content_path(@content)
    else
      flash.now[:error] = "Could not create content"
      render :action => "new"
    end
  end

  def edit
    @content = Content.find(params[:id])
    @content = @content.get_origin_type
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/content_helper.rb
module ContentHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/content/_article.html.erb
<li>
  <%= f.label :body %>
  <%= f.text_area :body %>
</li>

app/views/content/_form.html.erb
<li>
  <%= f.label :title %>
  <%= f.text_field :title %>
</li>
<li>
  <%= f.label :start_date %>
  <%= f.date_select :start_date %>
</li>

app/views/content/_news.html.erb
<%= render :partial => "article", :locals => {:f => f} %>
<li>
  <%= f.label :synopsis %>
  <%= f.text_area :synopsis %>
</li>

app/views/content/edit.html.erb
<% @page_title = "Edit #{@content.title}" %>

<%= form_for @content, :url => content_path(@content), :html => {:method => "put"} do |f| %>
  <fieldset>
    <legend><%= @page_title %></legend>
    <ul>
      <%= render :partial => "form", :locals => {:f => f} %>
      <li>
        <%= f.label :end_date %>
        <%= f.date_select :end_date, :include_blank => true %>
      </li>
      <%= render(:partial => @content.class.to_s.downcase, :locals => {:f => f}) %>
      <li>
        <%= f.submit "Save" %>
      </li>
    </ul>
  </fieldset>
<% end %>

app/views/content/new.html.erb
<% @page_title = "New content" %>

<%= form_for @content do |f| %>
  <fieldset>
    <legend><%= @page_title %></legend>
    <ul>
    <%= render :partial => "form", :locals => {:f => f} %>
      <li>
        <%= f.label :kind %>
        <%= f.select :kind, Content.children.map(&:to_s) %>
      </li>
      <li>
        <%= f.submit "Create" %>
      </li>
    </ul>
  </fieldset>
<% end %>

app/views/home/index.html.erb
<% @page_title = "Home" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Content-M&eacute;nage</title>
  <%= stylesheet_link_tag "reset" %>
  <%= javascript_include_tag "jquery.min", "rails", "application" %>
  <%= csrf_meta_tag %>
</head>
<body>
  <header id="masthead">
    <h1><%= @page_title || "Content M&eacute;nage".html_safe %></h1>
    <nav>
      <ul class="no-bullets">
        <li class="<%= "active " if params[:controller] == "home" %> first">Home</li>
        <li><%= link_to "New content", new_content_path %></li>
      </ul>
    </nav>
  </header>
  <div id="wrapper" class="wrapper">
    <div id="inner-wrapper" class="inner-wrapper">
      <%= yield %>
    </div>
  </div>
</body>
</html>